import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { sha256Fallback } from '../src/lib/sha256.ts';

// NIST CAVP byte-oriented SHA256ShortMsg.rsp (Len is expressed here in bytes).
// Published fixtures from the SHS byte test vectors, not generated by our code.
const knownAnswers = [
  {
    "length": 0,
    "message": "",
    "digest": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  },
  {
    "length": 1,
    "message": "d3",
    "digest": "28969cdfa74a12c82f3bad960b0b000aca2ac329deea5c2328ebc6f2ba9802c1"
  },
  {
    "length": 55,
    "message": "3ebfb06db8c38d5ba037f1363e118550aad94606e26835a01af05078533cc25f2f39573c04b632f62f68c294ab31f2a3e2a1a0d8c2be51",
    "digest": "6595a2ef537a69ba8583dfbf7f5bec0ab1f93ce4c8ee1916eff44a93af5749c4"
  },
  {
    "length": 56,
    "message": "2d52447d1244d2ebc28650e7b05654bad35b3a68eedc7f8515306b496d75f3e73385dd1b002625024b81a02f2fd6dffb6e6d561cb7d0bd7a",
    "digest": "cfb88d6faf2de3a69d36195acec2e255e2af2b7d933997f348e09f6ce5758360"
  },
  {
    "length": 57,
    "message": "4cace422e4a015a75492b3b3bbfbdf3758eaff4fe504b46a26c90dacc119fa9050f603d2b58b398cad6d6d9fa922a154d9e0bc4389968274b0",
    "digest": "4d54b2d284a6794581224e08f675541c8feab6eefa3ac1cfe5da4e03e62f72e4"
  },
  {
    "length": 63,
    "message": "e2f76e97606a872e317439f1a03fcd92e632e5bd4e7cbc4e97f1afc19a16fde92d77cbe546416b51640cddb92af996534dfd81edb17c4424cf1ac4d75aceeb",
    "digest": "18041bd4665083001fba8c5411d2d748e8abbfdcdfd9218cb02b68a78e7d4c23"
  },
  {
    "length": 64,
    "message": "5a86b737eaea8ee976a0a24da63e7ed7eefad18a101c1211e2b3650c5187c2a8a650547208251f6d4237e661c7bf4c77f335390394c37fa1a9f9be836ac28509",
    "digest": "42e61e174fbb3897d6dd6cef3dd2802fe67b331953b06114a65c772859dfc1aa"
  }
];

for (const { length, message, digest } of knownAnswers) {
  test(`SHA-256 NIST known answer: ${length} bytes`, async () => {
    const bytes = Uint8Array.from(Buffer.from(message, 'hex'));
    assert.equal(bytes.length, length);
    assert.equal(Buffer.from(await sha256Fallback(bytes.buffer)).toString('hex'), digest);
  });
}

test('SHA-256 RFC 6234 million-a known answer spans cooperative batches', async () => {
  const bytes = new Uint8Array(1_000_000).fill(97);
  assert.equal(Buffer.from(await sha256Fallback(bytes.buffer)).toString('hex'),
    'cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0');
});

test('SHA-256 agrees with independent Node and Web Crypto across binary padding and batch boundaries', async t => {
  const lengths = [2, 3, 54, 65, 119, 120, 121, 127, 128, 129,
    16383, 16384, 16385, 262143, 262144, 262145];
  for (const length of lengths) {
    const bytes = new Uint8Array(length);
    let seed = 0x12345678;
    for (let i = 0; i < length; i++) {
      seed ^= seed << 13; seed ^= seed >>> 17; seed ^= seed << 5;
      bytes[i] = seed;
    }
    const expected = createHash('sha256').update(bytes).digest('hex');
    assert.equal(Buffer.from(await sha256Fallback(bytes.buffer)).toString('hex'), expected, `${length} bytes`);
    assert.equal(Buffer.from(await crypto.subtle.digest('SHA-256', bytes)).toString('hex'), expected);
  }
  t.diagnostic(`binary agreement lengths: ${lengths.join(', ')}`);
});

test('fallback yields to a timer while hashing and stops when that timer aborts it', async () => {
  const controller = new AbortController();
  let timerRan = false;
  const timer = setTimeout(() => { timerRan = true; controller.abort(); }, 0);
  try {
    await assert.rejects(sha256Fallback(new ArrayBuffer(2 * 1024 * 1024), controller.signal),
      { name: 'AbortError' }, 'a synchronous or microtask-only hash would finish before the timer');
    assert.equal(timerRan, true);
  } finally {
    clearTimeout(timer);
  }
});
