# -*- coding: utf-8 -*-
# Calibre-Web Automated – fork of Calibre-Web
# Copyright (C) 2018-2026 Calibre-Web contributors
# Copyright (C) 2024-2026 Calibre-Web Automated contributors
# SPDX-License-Identifier: GPL-3.0-or-later
# See CONTRIBUTORS for full list of authors.

# SPDX-License-Identifier: GPL-3.0-or-later
"""Extraction anchors for SPA-only translatable strings.

The React SPA's English source strings ARE the gettext msgids (see
cps/api/i18n.py — the per-locale JSON catalog is derived from the same .po files
the classic UI uses). But pybabel only scans Python + Jinja (babel.cfg), so a
string that appears ONLY in the .tsx SPA is dropped from messages.pot on the
next re-extract — and msgmerge then marks its translations obsolete, so the SPA
silently falls back to English (this is exactly how #577's "Read now" → "Nu
lezen" was lost after the auto-translation job ran).

Referencing those SPA-only msgids here, with the gettext marker, keeps them in
the catalog across re-extracts. This module is never imported and does nothing at
runtime — babel reads the *source*, not the call result; ``_`` is a local no-op,
not flask_babel's request-scoped gettext (which can't run at import time).

Add a SPA-only msgid here the moment you introduce it in the frontend.
"""


def _(message):  # noqa: E743 - intentional gettext extraction marker, not the builtin
    return message


# #577 — the new-UI "open the reader" button. A distinct msgid from the "Read"
# read-status label (which is a past participle in many languages, e.g. nl
# "Gelezen") so the verb and the status can be translated separately.
_("Read now")
_("Open details for {title}")
_("Read {title}")

# Built-in magic-shelf names are canonical English database identity but are
# translated as request-local display text by the SPA API. They do not appear
# as literals in .tsx, so keep them in the SPA fuzzy-quality population here.
_("Recently Added")
_("Highly Rated")
_("Currently Reading")
_("Yet to Read")
_("Recent Publications")

# The SPA admin security endpoint sends these labels as data and Admin.tsx
# translates them at render time. Keep the complete backend-owned enums in the
# catalog: the TSX extractor cannot discover Python registry values.
_("Standard (username / password)")
_("LDAP")
_("OAuth / OpenID Connect")
_("Anonymous")
_("Unauthenticated")
_("Simple (service account)")
_("None")
_("TLS")
_("SSL")

# #573 — the new-UI series view's series-order sort options (Catalog.tsx). Only
# shown when viewing a single series, so the reader can order by position.
_("Series order")
_("Series order (reverse)")

# #572 — inline tag add/remove on the book detail page (quick-edit, no full
# editor). SPA-only strings, anchored so the auto-translation job keeps them.
_("Add tag")
_("New tag")
_("Remove tag")
# NB: the SPA's interpolate() uses {brace} placeholders, not gettext %(name)s —
# a %()s msgid renders its placeholder literally (was a latent bug here + in
# BulkBar). Keep SPA msgids on the {brace} form.
_("Remove tag {name}")
_("Rename tag {name}")
_("Tag name")
_("Tag name cannot be empty")
_("Save tag name")
_("Select format")
_("Could not rename tag")
_("Tag renamed to {name}")
_("You must be signed in")
_("You are not allowed to edit metadata")
_("Tag not found")
_("A tag with that name already exists")
_("Tag name must be text")
_("Tag name cannot contain commas")
_("Enter a valid tag name")
_("Could not load this page")
_("Page not found")

# Book detail completeness pass — star rating (parity with the classic detail
# page) and the "More by this author" browse strip that fills the page for
# sparse books. SPA-only strings (BookDetail.tsx / StarRating.tsx /
# MoreByAuthor.tsx), anchored so the auto-translation job keeps them.
_("Clear rating")
_("Not rated")
_("Yes")
_("No")
_("Email Message Body")
_("This Email has been sent via Calibre-Web NextGen.")
_("Rated {rating} out of 5")
_("More by {name}")

# Bulk-selection toolbar (BulkBar.tsx) — previously unanchored AND written with
# %(n)s, so they were dropped on re-extract and rendered the placeholder
# literally in a visible confirm dialog + button. Anchored on the {brace} form.
_("Merge {n} books into the first selected? The others are removed after their formats are copied over.")
_("Apply to {n} books")

# #736 cross-screen theme sweep — accessible names for the smart-shelf rule
# selects (previously unlabeled -> axe select-name critical).
_("Match condition")
_("Rule field")
_("Rule operator")
_("Could not load smart-shelf rules.")
_("Has Cover")
_("Series Index")
_("Read Status")
_("Has Hardcover ID")
_("In the past N days")
_("Not in the past N days")
_("is before / less than")
_("is on or before / at most")
_("is after / greater than")
_("is on or after / at least")
_("is between")
_("is not between")
_("does not begin with")
_("does not end with")
_("is empty")
_("is not empty")

# #736 — per-user theme picker
_("Appearance")
_("Theme")
_("System")
_("Light")
_("Dark")
_("Sepia")
_("High contrast")
_("Midnight (AMOLED)")
_("Match your device’s light or dark setting")
_("Theme saved.")
_("Could not save theme.")
_("Default theme for new accounts")
_("Applies to accounts created from now on. Everyone picks their own under Account → Theme.")


# ============================================================================
# Accessibility remediation (WCAG 2.2 AA sweep) — SPA-only strings introduced by
# the a11y pass: skip link, live-region announcements, ARIA labels for icon-only
# controls, reader/annotation color names, form/error messages. Anchored so the
# auto-translation job keeps them (babel does not scan .tsx).
# ============================================================================
_('Add a format')
_('Add rule')
_('Add to shelf')
_('Add your own')
_('App password label')
_('App passwords')
_('Author')
_('Authors (separate with &)')
_('Back to book')
_('Back to sign in')
_('Blue')
_('Book content')
_('Browse')
_('Change password')
_('Close')
_('Close menu')
_('Contents')
_('Convert failed.')
_('Convert to')
_('Convert to format')
_('Copy')
_('Could not change password.')
_('Could not create.')
_('Could not fetch cover.')
_('Could not load metadata.')
_('Could not load the book file ({status})')
_('Could not load your account.')
_('Could not save.')
_('Cover')
_('Cover image URL')
_('Cover update failed.')
_('Cover updated.')
_('Create smart shelf')
_('Create your account')
_('Dark')
_('Dark theme')
_('Delete')
# #803 — the new-UI book-detail whole-book delete control + confirm + states.
_('Delete book')
_('Delete "{title}"? This permanently removes the book and all its files from your library. This cannot be undone.')
_('Deleting…')
_('Could not delete this book.')
_('Delete the {fmt} file? The book stays; only this format is removed.')
_('Delete {fmt}')
_('Delete {n} book(s)? This cannot be undone.')
_('Description contains')
_('Deselect {title}')
_('Edit metadata')
_('Edit {title}')
# #928 — the saved default library view (#498) renders as a filtered library,
# so the notice strip that explains the subset lives on Catalog.tsx.
_('Showing your default library view.')
_('Show all books')
_('Edit default view')
_('Failed to load books.')
_('Failed to open the book.')
_('Generate')
_('Green')
_('Help')
_('Highlight color')
_('Import from Kobo')
_('Interface language')
_('Invalid username or password.')
# #701 — UI font preset picker (Account page + lib/fonts.ts)
_('UI body font')
_('UI display font')
_('Default (Optima / Sans-Serif)')
_('Default (Bookish Serif)')
_('System Sans-Serif')
_('Bookish Serif')
_('Monospace')
_('Label (e.g. KOReader on phone)')
_('Languages (comma separated)')
_('Light')
_('Light theme')
_('Login failed.')
_('Mark read')
_('Mark unread')
_('Merge')
_('Metadata applied to {n} book(s).')
_('New password for “{label}” — copy it now, it won’t be shown again:')
_('New passwords do not match.')
_('No books here.')
_('No results for "{q}".')
_('No suggestions')
_('No {filter} books here.')
_('Password changed.')
_('Paste URL')
_('Private shelf')
_('Profile')
_('Profile saved.')
_('Public shelf')
_('Publisher')
_('Publishers (comma separated)')
_('Read')
_('Reading progress')
_('Red')
_('Registration failed.')
_('Remove {name}')
_('Request failed.')
_('Reset')
_('Reset your password')
_('Revoke {label}')
_('Save changes')
_('Save failed.')
_('Save profile')
_('Saved.')
_('Saving…')
_('Search')
_('Search failed.')
_('Search for metadata')
_('Metadata providers')
_('Loading providers…')
_('Could not load providers.')
_('Could not update provider.')
_('{provider}: {state}')
_('On')
_('Off')
_('Search results')
_('Search the library')
_('Select {title}')
_('Sepia')
_('Sepia theme')
_('Series')
_('Series position {n}')
# #657 — series name + position shown under the cover on book cards (BookCard.tsx)
_('{series} #{n}')
_('Sign in')
_('Sign in failed. Please try again.')
_('Skip to content')
_('Some fields could not be saved.')
_('Table of contents')
_('Tags (comma separated)')
_('Title')
_('Unread')
_('Update password')
_('Upload')
_('Choose books to upload')
_('Upload failed.')
_('Upload image')
_('Uploading…')
_('Yellow')
_('e.g. MOBI')
_('{format} reader')
_('{name} API key')
_('{n} book(s) added to the shelf.')
_('{n} book(s) deleted.')
_('{n} marked as read.')
_('{n} marked as unread.')
_('{n} selected')
_('{pct}% read')
# "What's new" in-app feature log (SPA /whats-new + the Help menu entry). The
# page CHROME is localized; the per-release entry copy in data/whatsNew.ts is
# English by design (documented on the page). Category names double as the chip
# labels AND the WhatsNewCategory union values — keep them in sync with
# frontend/src/data/whatsNew.ts if that union ever changes.
_("What's new")
_("Help — new updates available")
_("The latest features and fixes in Calibre-Web NextGen — newest first.")
_("{n} update")
_("{n} updates")
_("No release notes yet — check back after the next update.")
_("The interface is translated into your language; these update notes are written in English.")
# Category chips (must match the WhatsNewCategory union)
_("Reading")
_("Grid view")
_("Library")
_("List view")
_("Sync")
_("Account")
_("Admin")
_("Under the hood")
# "Try it" deep-link button labels (data-authored, but stable enough to anchor
# so a reader's locale can translate the call-to-action).
_("Open your library")
_("Browse tags")
_("Open the table view")
_("Review duplicates")
_("Open your shelves")
_("Manage sync & app passwords")
_("Check your e-reader address")
_("Create an app password")
_("Browse series")
_("Browse authors")
_("Browse languages")
_("Open Table view")
_("Open Admin")
_("Open account settings")
_("Browse Discover")
_("Explore your library")
_("Go to Upload")
_("Open search")
# Metadata edit — Hardcover editions drill-down (EditBook.tsx)
_("Editions")
_("Back to New UI")
_("Back to results")
_("No editions found for this book.")
# Metadata edit — full-record "View all details" overlay (EditBook.tsx)
_("View all details")
_("Result details")
_("Published")
_("Format")
_("Source")
# #585 — in-sidebar "Customize" capsule + inline edit mode (Sidebar.tsx +
# SidebarEditList.tsx): reorder and hide/restore sidebar sections from the new UI.
_("Customize")
_("Customize sidebar")
_("Customize navigation")
_("Done")
_("Reset to default")
_("Always shown")
_("Editing sidebar. Reorder or hide sections, then tap Done.")
_("Editing cancelled.")
_("Drag to reorder. Tap ✕ to hide a section. Arrow keys move the focused handle.")
_("Sidebar saved.")
_("Sidebar reset to default.")
_("{label} moved to position {pos} of {total}")
_("Reorder {label} (position {pos} of {total}). Use arrow keys to move.")
_("Delete {label}")
_("Restore {label}")
_("{label} hidden")
_("{label} restored")
_("Could not save sidebar. Please try again.")

# #780 / #665 — manual library scan button in the catalog toolbar (Catalog.tsx).
# The SPA had no equivalent of the classic header's "Refresh Library" action.
# Deliberately a distinct (lowercase-l) msgid from the classic "Refresh Library"
# so the button can read in sentence case; anchored so the auto-translation job
# keeps it across re-extracts.
_("Refresh library")


# ==== BEGIN AUTOGEN (scripts/extract_spa_strings.py --write) ====
# Auto-anchored SPA-only msgids — every t('literal') and static label
# property in frontend/src that
# is not already anchored above. Do NOT edit by hand; run
#   python scripts/extract_spa_strings.py --write
# after adding or removing SPA strings. The CI gate
# (tests/unit/test_spa_strings_anchored.py) fails if this drifts.
_("(replace cover)")
_("2:3 (publisher cover — no padding for typical covers)")
_("3:4 (generic)")
_("A duplicate scan is already running. This list updates when it finishes.")
_("A few random picks from your library")
_("A one-time full duplicate scan is needed. Use “Scan for duplicates” above to run it.")
_("RAG search")
_("RAG search failed.")
_("RAG search is not available for this account.")
_("API keys")
_("About")
_("Account settings")
_("Account: {name}")
_("Add bookmark")
_("Add identifier")
_("Add note")
_("Add to favorites")
_("Admin group")
_("Advanced")
_("Advanced search")
_("After")
_("All")
_("All shelves")
_("Allow remote (magic-link) login")
_("Allowed groups (comma-separated)")
_("Animated page turns")
_("Any")
_("Any format")
_("Any language")
_("Any series")
_("Any tags")
_("Apply selected")
_("Apply to all selected (only filled fields change; replaces existing values):")
_("Applying…")
_("Approve long OCR job")
_("Archive")
_("Archived")
_("Ask in Discord")
_("Authentication")
_("Authentication & security")
_("Author A–Z")
_("Author Z–A")
_("Authorised — signing you in…")
_("Authorize URL")
_("Authors")
_("Auto-create users")
_("Auto-create users on first login")
_("Automatic OCR page limit")
_("Back to edit metadata")
_("Back to library")
_("Back to the classic view")
_("Background processing")
_("Base DN")
_("Basic configuration")
_("Before")
_("Black")
_("Book")
_("Book density")
_("Book not found.")
_("Book {number}")
_("Bookmark")
_("Bookmarks")
_("Books")
_("Books per page")
_("Books that are not on a Kobo-sync shelf are then removed from the device on its next sync. They stay in your library here.")
_("Border fill style")
_("Browser")
_("Built-in providers (leave blank to disable):")
_("Bulk actions")
_("CA certificate path")
_("CWA settings (ingest/convert)")
_("Can upload books")
_("Cancel")
_("Cancel rename")
_("Cancel title edit")
_("Cancel {task}")
_("Categories")
_("Certificate file path")
_("Certificate path")
_("Change cover")
_("Checking…")
_("Choose a cover")
_("Choose a cover image to upload")
_("Choose an image…")
_("Choose fields")
_("Choose your theme")
_("Clear default")
_("Clear selection")
_("Client ID")
_("Client secret")
_("Client secret (leave blank to keep)")
_("Close reader")
_("Columns")
_("Comfortable")
_("Comma-separated names")
_("Comma-separated tags")
_("Compact")
_("Configured")
_("Confirm new password")
_("Continuous scroll")
_("Convert")
_("Convert before sending")
_("Convert from")
_("Copied to clipboard")
_("Copy link")
_("Could not create shelf.")
_("Could not create the shelf.")
_("Could not delete shelf.")
_("Could not load candidates.")
_("Could not load duplicates.")
_("Could not load highlights.")
_("Could not load stats.")
_("Could not load tasks.")
_("Could not load the PDF file ({status})")
_("Could not load the book.")
_("Could not load this PDF file.")
_("Could not load this text file.")
_("Could not load users.")
_("Could not open this book.")
_("Could not read OCR status.")
_("Could not read the RAG status.")
_("Could not read this comic archive.")
_("Could not reload metadata")
_("Could not rename shelf.")
_("Could not reset password.")
_("Could not save OCR settings.")
_("Could not save order.")
_("Could not save reading position. It will be retried automatically.")
_("Could not save the default library filter.")
_("Could not save the shelf.")
_("Could not save title.")
_("Could not start OCR.")
_("Could not start the duplicate scan.")
_("Could not update shelf.")
_("Could not update your account setting.")
_("Couldn’t start a magic link. Please try again.")
_("Cover locked")
_("Cover not reachable")
_("Cover save failed.")
_("Cover updated from the selected result.")
_("Create")
_("Create account")
_("Create an account")
_("Create failed.")
_("Create shelf and add book")
_("Create user")
_("Created {name}.")
_("Creating…")
_("Current")
_("Current cover")
_("Current password")
_("Currently reading")
_("Custom border colour")
_("Custom columns")
_("Database & library path")
_("Date added")
_("Default (System Sans-Serif)")
_("Default book language")
_("Default interface language")
_("Default library filter cleared.")
_("Default library filter saved.")
_("Default roles for new OAuth users:")
_("Defaults live in Admin → Configuration → Kobo sync.")
_("Delete books")
_("Delete failed.")
_("Delete shelf \"{name}\"? This cannot be undone.")
_("Delete this smart shelf? Your books are not affected.")
_("Delete user \"{name}\"? Their shelves and reading data are removed too.")
_("Delete {name}")
_("Deleted {name}.")
_("Dense")
_("Describe an idea, scene, fact, quote, technology, or topic…")
_("Description")
_("Disable standard password login")
_("Discover")
_("Discover picks updated.")
_("Discover — Random Picks")
_("Dismiss")
_("Dismiss this group")
_("Document OCR")
_("Documentation")
_("Documents above this limit require explicit confirmation and are not started automatically.")
_("Done reordering")
_("Download")
_("Download PDF")
_("Drop files here, or click to choose")
_("Duplicate")
_("Duplicate books")
_("Duplicate detection settings")
_("Duplicate scan started. It runs in the background — this list updates when it finishes.")
_("Duplicates")
_("E-reader preview")
_("Each type (isbn, amazon, google, doi…) may appear once.")
_("Edge blur — soft bokeh border")
_("Edge mirror — extend the artwork (recommended)")
_("Edit")
_("Edit note")
_("Edit public shelves")
_("Edit smart shelf")
_("Edit title for {title}")
_("Email")
_("Email (SMTP) server")
_("Email (optional)")
_("Email claim")
_("Email me a reset")
_("Email settings saved.")
_("Embedding")
_("Embedding model")
_("Enable Kobo sync")
_("Encryption")
_("Expires in")
_("Expose only selected shelves over OPDS")
_("Failed jobs")
_("Failed to load shelves.")
_("Failed to load.")
_("Favorite")
_("Favorited")
_("Favorites")
_("Fetch")
_("Fetch metadata from web")
_("Files")
_("Files are queued for the library's ingest process and appear once imported.")
_("Filter {items}")
_("Filter {items}…")
_("Filters")
_("Font")
_("Font size")
_("Forgot password?")
_("Format queued — it will appear once processed.")
_("Formats")
_("Formats — exclude")
_("Formats — include")
_("From address")
_("Full screen")
_("Full user table & restrictions")
_("Generate a new link")
_("Give your smart shelf a name.")
_("Go to your library")
_("Gradient — palette-matched top/bottom blend")
_("Group claim")
_("Group members field")
_("Group name")
_("Group object filter")
_("HTML is allowed and sanitized on display.")
_("Header name")
_("Help & support")
_("Help menu")
_("Hidden")
_("Hide")
_("Hide Discover section")
_("Hide fields")
_("Hide password")
_("Highlight")
_("Highlights")
_("Highlights and notes")
_("Hot")
_("Hot — Most Downloaded")
_("Icon")
_("Identifier type")
_("Identifier value")
_("Identifiers")
_("Idle")
_("Imported as")
_("In your book")
_("Include neighboring text for context")
_("Indexed books")
_("Issuer / base URL")
_("It may have moved, or it might still live in the classic interface.")
_("KOReader Progress")
_("Key file path")
_("Key path")
_("Kobo Clara HD / 2E / BW / Colour (1072×1448)")
_("Kobo Libra Color / Libra 2 (1264×1680)")
_("Kobo sync on")
_("Language")
_("Languages")
_("Languages — include")
_("Last modified")
_("Last synced")
_("Library settings")
_("Line height")
_("Justify text")
_("Load more")
_("Loading")
_("Loading new Discover picks.")
_("Loading…")
_("Location")
_("Lock cover")
_("Login")
_("Login button text")
_("Login method")
_("Login with")
_("Logs")
_("Looks good")
_("Low-res")
_("Magic link")
_("Magic link QR code")
_("Make private")
_("Make public")
_("Make this my default library view")
_("Manage admin role from OAuth group")
_("Manage shelves")
_("Mark as read")
_("Mark as unread")
_("Match")
_("Matched")
_("Max")
_("Max authors shown")
_("Maximum rating")
_("Member user filter")
_("Metadata URL (OIDC auto-discovery)")
_("Min")
_("Minimum rating")
_("More cover options (search providers, e-reader preview)")
_("More server configuration")
_("Move down")
_("Move up")
_("My account")
_("Name")
_("Need to report an issue? Try the new")
_("New")
_("New password")
_("New shelf name")
_("New shelf name…")
_("New shelf…")
_("New smart shelf")
_("New user")
_("Newest")
_("Newest published")
_("Next page")
_("No PDF annotations yet. Use the Annotate tools above the document.")
_("No bookmarks yet.")
_("No books match this smart shelf right now.")
_("No books match those criteria.")
_("No candidates found yet. Try a different search or refresh.")
_("No contents found.")
_("No duplicate groups found.")
_("No excerpt available.")
_("No excluded tags")
_("No highlights yet.")
_("No matching passages were found.")
_("No matching {items} for \"{query}\".")
_("No pages found in this comic.")
_("No shelves yet — create one below.")
_("No shelves yet. Create one above to start collecting books.")
_("No sources need a key.")
_("No supported reader format is available.")
_("No tasks running.")
_("No {items} yet.")
_("Not configured")
_("Not enabled")
_("Not indexed")
_("Not set")
_("Note")
_("Notes")
_("OCR and RAG indexing completed.")
_("OCR completed; RAG indexing is running.")
_("OCR failed.")
_("OCR is processing the PDF.")
_("OCR is queued.")
_("OCR job queued. You can leave this page; processing continues in the background.")
_("OCR page limit saved.")
_("OCR processing…")
_("OCR queued")
_("OCR running")
_("OCR settings")
_("OCR was not started.")
_("Oldest")
_("Oldest published")
_("On another device where you’re already signed in, scan this code or open the link below to authorise this device.")
_("One column")
_("Open Account")
_("Open book")
_("Open full annotations page")
_("Open navigation")
_("Open the classic interface")
_("Open the link below on your signed-in device.")
_("Open with browser PDF viewer")
_("OpenLDAP server")
_("Opens in classic view")
_("PDF annotation changes could not be saved. Retry the edit.")
_("PDF reader")
_("Page")
_("Page count changes with font, margins, and window size; progress remains stable.")
_("Page margins")
_("Page {number}")
_("Pages")
_("Pages marked below open in the classic view. Changes there apply to the whole server.")
_("Password")
_("Password (leave blank to keep)")
_("Pending")
_("Pick a cover from any source we support, paste a URL, upload a file, or use the cover embedded in the book itself.")
_("Picked up {label}. Drag to reorder, release to drop.")
_("Port")
_("Preparing your magic link…")
_("Previous page")
_("Progress")
_("Public")
_("Published after")
_("Published before")
_("Publisher / serif")
_("Publishers")
_("RAG index status")
_("RAG indexing")
_("RAG queued")
_("Random books shown")
_("Rating")
_("Rating (stars)")
_("Ratings")
_("Read aloud")
_("Read status")
_("Read status filter")
_("Reader settings")
_("Reader settings are saved to your account and follow you across devices.")
_("Reader tools")
_("Reading mode")
_("Reading position could not be saved. Retrying…")
_("Recipient(s)")
_("Redirect host (full URL)")
_("Refresh")
_("Registering…")
_("Reload")
_("Reload metadata from disk")
_("Reloading…")
_("Remember me")
_("Remove from favorites")
_("Remove from shelf")
_("Remove identifier")
_("Remove rule")
_("Rename")
_("Reorder")
_("Replace cover with this one?")
_("Replace cover?")
_("Report Issue on Discord")
_("Report Issue on GitHub")
_("Require group membership")
_("Reranker")
_("Reranker model")
_("Reset password for {name}")
_("Reset password for {name}? Their current password will stop working and a replacement will be emailed.")
_("Result limit")
_("Reverse-proxy header login")
_("Rows per load")
_("Run OCR")
_("Run OCR again")
_("Run time")
_("SMTP server")
_("SSL/TLS")
_("STARTTLS")
_("Save")
_("Save OCR limit")
_("Save email settings")
_("Save name")
_("Save security settings")
_("Save settings")
_("Saved. Restart the server for the login changes to take effect.")
_("Scan for duplicates")
_("Scheduled tasks")
_("Scopes")
_("Search book contents")
_("Search in book")
_("Search inside the full text of your indexed books, not only titles and metadata.")
_("Search mode")
_("Search title, author…")
_("Searching every source…")
_("Searching…")
_("Security settings saved.")
_("See how each cover looks padded for your device")
_("Select")
_("Select multiple")
_("Selected text actions")
_("Send")
_("Send failed.")
_("Send to e-reader")
_("Send-to-eReader email")
_("Sending…")
_("Series index")
_("Series view")
_("Series — include")
_("Serve over HTTPS")
_("Server SSL / HTTPS")
_("Server announcement (shown to all users)")
_("Server host")
_("Service account (DN)")
_("Service password")
_("Service password (leave blank to keep)")
_("Set a metadata URL to auto-fill the endpoints below, or enter them manually.")
_("Settings saved.")
_("Shelf name")
_("Shelf not found.")
_("Shelves")
_("Show Discover section")
_("Show Table view")
_("Show all {count} tags")
_("Show all {items}")
_("Show books in language")
_("Show e-reader previews on each candidate")
_("Show fewer tags")
_("Show hidden books")
_("Show password")
_("Show surrounding context")
_("Shuffle picks")
_("Sign in with a magic link")
_("Sign out")
_("Signing in…")
_("Site title")
_("Smart shelf not found.")
_("Smart shelves")
_("Solid: average colour of the cover")
_("Solid: custom colour")
_("Solid: most-common colour in the cover")
_("Some sources need a key for better covers")
_("Something went wrong")
_("Something went wrong. Try again.")
_("Sort order")
_("Source details")
_("Sources")
_("Started reading")
_("Starting scan…")
_("Starting…")
_("Statistics")
_("Statistics dashboard")
_("Status")
_("Stop reading aloud")
_("Support on Ko-fi →")
_("Sync error")
_("Sync only my selected shelves")
_("Sync only selected shelves to Kobo")
_("Synced")
_("Table view")
_("Tag")
_("Tags")
_("Tags — exclude")
_("Tags — include")
_("Target aspect ratio")
_("Task")
_("Tasks")
_("Tasks remaining")
_("Technical details")
_("Text chunks")
_("Text width")
_("That URL is not a usable image.")
_("The PDF reader could not initialize its navigation or annotation plugins.")
_("The page refreshes processing status automatically.")
_("This PDF has {pages} pages, above the automatic OCR limit of {limit}. Processing may take a long time and use significant CPU.")
_("This magic link expired. Generate a new one to try again.")
_("This page doesn't exist here.")
_("This page ran into an error and could not be displayed. Your library is fine — reloading usually fixes it.")
_("This shelf is empty. Add books from any book's page.")
_("Title A–Z")
_("Title Z–A")
_("Title, author, or ISBN")
_("Token URL")
_("Top Rated")
_("Trust authentication header")
_("Turn pages by clicking the left or right side")
_("Two columns")
_("UI / display configuration")
_("Unarchive")
_("Unhide")
_("Unknown model")
_("Unlock the cover above to apply a new one.")
_("Unlock the cover to change it")
_("Untitled")
_("Update failed.")
_("Upload as cover")
_("Upload books")
_("Use these to connect OPDS readers or KOReader sync without your main password.")
_("Use this cover")
_("User")
_("User administration")
_("User object filter")
_("Userinfo URL")
_("Username")
_("Username claim")
_("Vector sync")
_("Versions")
_("View")
_("View settings")
_("Viewer")
_("Waiting for you to authorise…")
_("What do you want to find?")
_("When locked, fetching metadata will not overwrite this cover.")
_("When reading progress was first synced")
_("Working")
_("Your Kobo is still set to sync your whole library, so marking this shelf does nothing on its own. Switch your account to shelf-only syncing to make it take effect.")
_("Your Library")
_("Your browser cannot play this audio format.")
_("Your personal digital library")
_("Your saved e-reader address is shown — change it for this send only.")
_("all rules")
_("any rule")
_("books")
_("books indexed")
_("books match")
_("copies")
_("e-reader")
_("e.g. Unread sci-fi")
_("eReader email subject")
_("pages")
_("results")
_("shared")
_("to")
_("type (isbn, amazon, doi…)")
_("value")
_("you")
_("{count} book")
_("{count} books")
_("{count} characters")
_("{count} file queued for import")
_("{count} file rejected")
_("{count} files queued for import")
_("{count} files rejected")
_("{count} pages")
_("{count} result")
_("{count} results")
_("{count} results for \"{query}\"")
_("{field} (comma separated)")
_("{n} found")
_("{ok} of {total} sources answered")
_("…or paste an image URL")
_("← Back to sign in")
_("← Library")
# ==== END AUTOGEN ====

# Foliate visible-page LLM translation profiles, controls, and status text.
_("API key")
_("API key saved")
_("Additional HTTP headers (JSON)")
_("Additional headers must be a valid JSON object.")
_("Automatically translate the current page")
_("Cache full translated pages")
_("Preload one translated page ahead")
_("Available models")
_("Base URL")
_("Cached")
_("Choose a model to edit the profile")
_("Configure page translation")
_("Connection successful.")
_("Connection test failed.")
_("Could not delete the translation profile.")
_("Could not load models.")
_("Could not save the translation profile.")
_("Custom OpenAI-compatible")
_("Delete this translation profile?")
_("Detect automatically")
_("Endpoint path")
_("Groq")
_("LLM profile")
_("Leave blank to keep the saved key")
_("Leave blank to use the built-in literary translation prompt.")
_("Load models")
_("Loading translation profiles…")
_("Max output tokens")
_("Mistral")
_("Model")
_("No API key")
_("No profile selected")
_("No visible text was found on this page.")
_("Ollama")
_("OpenRouter")
_("Original")
_("Page language view")
_("Page translation")
_("Page translation failed.")
_("Private endpoints are blocked. Set CWNG_READER_TRANSLATION_ALLOW_PRIVATE_ENDPOINTS=true on the server to use Ollama or another LAN model.")
_("Profile name")
_("Provider preset")
_("Request JSON output when supported")
_("Retry")
_("Source language")
_("Target language")
_("Temperature")
_("Test connection")
_("Timeout (seconds)")
_("Translating the current page…")
_("Translation")
_("Translation profile deleted.")
_("Translation profile saved.")
_("Translation prompt")
_("{count} models loaded.")

_("Add")
_("OpenCode Zen")
_("OpenCode Go")

_("NVIDIA NIM")
_("The book is already in the target language.")
_("The selected text is already in the target language.")
