/**
 * Canonical SPA route table. App.tsx renders these exact patterns and the
 * post-auth redirect classifier matches against the same values, so a classic
 * route can never drift into being treated as a client-side route.
 */
export const SPA_ROUTES = {
  reader: '/read/:id',
  nativeReader: '/view/:id/:format',
  editBook: '/book/:id/edit',
  coverPicker: '/book/:id/cover',
  annotations: '/book/:id/annotations',
  book: '/book/:id',
  authors: '/authors',
  author: '/authors/:id',
  seriesList: '/series',
  series: '/series/:id',
  tags: '/tags',
  tag: '/tags/:id',
  publishers: '/publishers',
  publisher: '/publishers/:id',
  languages: '/languages',
  language: '/languages/:id',
  ratings: '/ratings',
  rating: '/ratings/:id',
  ccList: '/cc',
  cc: '/cc/:id',
  formats: '/formats',
  format: '/formats/:id',
  shelves: '/shelves',
  shelfNew: '/shelves/new',
  shelfEdit: '/shelf/:id/edit',
  shelf: '/shelf/:id',
  hot: '/hot',
  discover: '/discover',
  rated: '/rated',
  favorites: '/favorites',
  archived: '/archived',
  search: '/search',
  aiSearch: '/ai-search',
  account: '/account',
  moonReader: '/account/moonreader',
  global: '/global',
  deviceDetail: '/account/devices/:id',
  devices: '/account/devices',
  upload: '/upload',
  admin: '/admin',
  adminDevices: '/admin/devices',
  adminAcquisition: '/admin/acquisition',
  findBooks: '/find-books',
  whatsNew: '/whats-new',
  about: '/about',
  tasks: '/tasks',
  table: '/table',
  duplicates: '/duplicates',
  magicNew: '/magic/new',
  magicEdit: '/magic/:id/edit',
  magicView: '/magic/:id',
  magic: '/magic',
  library: '/',
} as const;

export const AUTH_ROUTES = {
  login: '/login',
  magicLink: '/magic-link',
} as const;

export const SPA_ROUTE_PATTERNS = Object.values(SPA_ROUTES);
